# Кто владелец репозитория
owner: mrGhostage        # твой GitHub username
repo: youme-status # имя репозитория со статусом

# Список сайтов, которые мониторим
sites:
  - name: Youme Front (prod)
    url: https://youme.gg

  - name: Youme API (prod)
    url: https://api2.youme.gg/healthz

  - name: Youme Front (test)
    url: https://test.youme.gg

  - name: Youme API (test)
    url: https://test.api2.youme.gg/healthz

# Кому назначать инциденты в Issues (опционально)
assignees:
  - mrGhostage

# Настройки статус-сайта
status-website:
  # cname: status.youme.gg   # если будешь делать отдельный домен, иначе можно удалить
  baseUrl: /youme-gg-status  # если без кастомного домена, раскомментировать и указать имя репо
  name: Youme.gg Status
  theme: night    # тема оформления (есть несколько вариантов)
